### ISSUE TITLE
Changing "blacklisted_min_runtime" causes unexpected results when using CLI. 

### ISSUE THREAD

**Issue by MollyBe** [l3uddz/traktarr#101]
Changing "blacklisted_min_runtime" causes unexpected results when using CLI to import movies.

When running the following command we see unexpected output based on blacklisted_min_runtime:
`traktarr movies -t trending -l 100 -s votes`
With blacklisted_min_runtime set at 40 we see:
`Retrieved Trakt 'Trending' movies list, movies found: 1285`
and with it set to 1 we see:
`Retrieved Trakt 'Trending' movies list, movies found: 993`

I would expect the list to be the same each time, or at most movies found to increase as we decrease blacklisted minimum runtime. We are seeing the opposite here. 

I also observed no more movies being imported when blacklist runtime was set to 40. Strangely, I observed movies being imported with runtimes over 40 minutes when blacklist runtime was set to 1.

Reproducible with Master (latest)

Near the time of writing this trakt.tv had:
1002 in trending
1436 in anticipated

**Comment by desimaniac** [comment]
Update your Traktarr

**Comment by MollyBe** [comment]
Updated Traktarr and am now seeing expected results. I ran the follow 3 times with the same result each time.

With the following command: `traktarr movies -t trending -l 100 -s votes`
and with blacklisted_min_runtime set at 1 we see: `Retrieved Trakt 'Trending' movies list, movies found: 1176`
or with blacklisted_min_runtime set at 40 we see: `Retrieved Trakt 'Trending' movies list, movies found: 1170`
