### ISSUE TITLE
Add special keyword to allow all languages

### ISSUE THREAD

**Issue by nbo21** [l3uddz/traktarr#113]
I would like an option to allow all languages in the filters section.

I don't think it's very practical to add a long list language codes to the allowed list if you want to accept everything. Adding a keyword i.e. `["all"]` would be very useful.

**Comment by rbraunschweig** [comment]
You can also use the `ignore` keyword in `allowed_languages`.

**Comment by nbo21** [comment]
That's good to know, thank you.
