### ISSUE TITLE
Option " --include_non_acting_roles" not working for CLI commands

### ISSUE THREAD

**Issue by Rubeast** [l3uddz/traktarr#117]
I was asked in the discord channel to post this here.
On the wiki you can find examples CLI.
https://github.com/l3uddz/traktarr#examples-cli

The last example is:
traktarr movies -t person -a 'tom cruise' --include_non_acting_roles -l 10

When I execute that I receive: 
"Error: no such option: --include_non_acting_roles"

Without that option, the command works fine.
But I was looking for a way to add movies from a certain director. (Don't even know if this is the best way)

**Comment by desimaniac** [comment]
Thanks. I’ll take a look later.

**Comment by desimaniac** [comment]
The command argument has dashes, not underlines. 

```
traktarr movies --help
```
```
--include-non-acting-roles      Include non-acting roles such as 'As Himself', 'Narrator', etc.
                                  Requires the 'person' list option with the 'actor' argument.
```

**Comment by desimaniac** [comment]
Corrected the example in the readme. Thanks for pointing it out.

**Comment by desimaniac** [comment]
As for director search, try `-a <director name> -include-non-acting-roles`
