### ISSUE TITLE
Error when running traktarr

### ISSUE THREAD

**Issue by ZoneChase** [l3uddz/traktarr#160]
![image](https://user-images.githubusercontent.com/22301693/151642074-de9905ca-efab-4295-bd3a-c5dc3fe40581.png)

**Comment by saltydk** [comment]
Config issue.

**Comment by ZoneChase** [comment]
I manage to fix the config file. But i can't seem to get it working. i add new show to trakt.tv but it is not sending to radarr.

**Comment by ZoneChase** [comment]
![image](https://user-images.githubusercontent.com/22301693/151649578-d7c038b3-0726-4407-aa6d-d2260dfb31bc.png)

how am i suppose to know what is happening? i check both radarr and sonar and neither show or movie was added.

**Comment by saltydk** [comment]
All that image shows is that it'll do something an hour after the displayed time. Automatic mode isn't really what you'd use for testing.

**Comment by ZoneChase** [comment]
![image](https://user-images.githubusercontent.com/22301693/151701247-7595e6bc-ff33-4715-82b5-b78d5d1f3792.png)

what am i missing here?

**Comment by saltydk** [comment]
Should really go to https://discord.io/cloudbox for support.
