### ISSUE TITLE
Error running traktarr.py

### ISSUE THREAD

**Issue by RusticPotatoes** [l3uddz/traktarr#172]
**Describe the bug**
traktarr.py file is not running due to import failure on 'click' module 

**To Reproduce**
1. Running ./traktarr.py 
2. You get the error 

```log
/traktarr # ./traktarr.py
Traceback (most recent call last):
  File "./traktarr.py", line 7, in <module>
    import click
ModuleNotFoundError: No module named 'click'
```

**Expected behavior**
You should see the default help output

**System Information**

 - Traktarr Version: last docker updated 5 days ago 
 - Operating System: docker image https://hub.docker.com/r/eafxx/traktarr

**Comment by saltydk** [comment]
Not our image.
