### ISSUE TITLE
Cant add anything

### ISSUE THREAD

**Issue by xman0980** [l3uddz/traktarr#30]
ERROR      - traktarr                            - show                                - FAILED adding The 100 (2014) with tags: None
ERROR      - traktarr                            - movies                              - FAILED adding Moana (2016)

Everything I try to add gives me an error.

I'm using  version 1.2.1

"filters": {
    "movies": {
      "allowed_countries": ["us"],
      "allowed_languages": [],
      "blacklist_title_keywords": ["barbie"],
      "blacklisted_genres": [],
      "blacklisted_max_year": 2019,
      "blacklisted_min_runtime": 30,
      "blacklisted_min_year": 1950,
      "blacklisted_tmdb_ids": []
    },
    "shows": {
      "allowed_countries": ["us"],
      "allowed_languages": [],
      "blacklisted_genres": ["talk-show", "anime", "news"],
      "blacklisted_max_year": 2019,
      "blacklisted_min_runtime": 15,
      "blacklisted_min_year": 1950,
      "blacklisted_networks": [],
      "blacklisted_tvdb_ids": []
  }
  },
  "notifications": {
    "verbose": true
  },
  "radarr": {
    "api_key": "XXXX",
    "profile": "HD-1080p",
    "root_folder": "XXXXX",
    "url": "http://localhost:7878/"
  },
  "sonarr": {
    "api_key": "XXXXX",
    "profile": "HD-1080p",
    "root_folder": "XXXX",
    "tags": {},
    "url": "http://localhost:8989/"
  },
  "trakt": {
    "client_id": "XXXXX",
    "client_secret": "XXXX"
  }
}

**Comment by l3uddz** [comment]
Turn debug mode on and give some logs pls.

**Comment by xman0980** [comment]
[activity.log](https://github.com/l3uddz/traktarr/files/2065404/activity.log)

traktarr --logfile /opt/traktarr/activity.log show -id the-100

**Comment by l3uddz** [comment]
try removing the / from the end of your sonarr + radarr urls

**Comment by l3uddz** [comment]
@horjulf seems this issue has popped up again

**Comment by xman0980** [comment]
[noslash.log](https://github.com/l3uddz/traktarr/files/2065451/noslash.log)
Still errors out.

**Comment by l3uddz** [comment]
well the issue is, its sending an add request, and instead of sonarr just returning the series that was added, its returning the entire series list. 

this issue has happened before: https://github.com/l3uddz/traktarr/issues/7

see if how he fixed it helps here, otherwise will need to see what @horjulf says as he too encountered the same issue, but he made some changes which should have resolved it if properly configured.

**Comment by xman0980** [comment]
I got it working.
This is how I setup the URL in the config 
"url": "http://127.0.0.1:8989/sonarr

**Comment by l3uddz** [comment]
Glad you're up and running.
