### ISSUE TITLE
Ignore tags when adding from watchlist

### ISSUE THREAD

**Issue by 4everfun** [l3uddz/traktarr#31]
Any blacklist tag should be ignored when adding new shows/movies from a trakt watchlist. Since it's on your watchlist you'd want it anyway, whether it's not the correct country or language according to your settings.

**Comment by mitchellklijs** [comment]
Fixed by: https://github.com/l3uddz/traktarr/pull/32

**Comment by l3uddz** [comment]
@mitchellklijs pr has been merged into the develop branch, should be good to go. close the issue if its as you expect. also some suggestions would be handy if you have any other requests.
