### ISSUE TITLE
New features, do they belong in traktarr?

### ISSUE THREAD

**Issue by wishbones** [l3uddz/traktarr#40]
Hey there l3uddz, in a private fork of this repo, I've added a few features. Maybe you'd accept PRs for them? They expand what traktarr does, so maybe you're not comfortable with that.

I've already coded up:

* Add the collection tag to movies in Plex based off a Trakt list
  The idea is to watch a Trakt list and automatically tag the matching Plex films with a collection that is the name of the Trakt list. This complements the original traktarr feature of adding a list to radarr nicely. You can use Traktarr to add a James Bond list, then create a "James Bond" collection in Plex.
`traktarr tagmovies -t "https://trakt.tv/users/danio1972/lists/james-bond-series"`
This uses the [`plexapi`](https://github.com/pkkid/python-plexapi) module.

* Import a text or csv file of movie names and years into a Trakt list
  Once I had Trakt list downloading and collection tagging, I needed a way to make lists easily. My workflow now is to troll the web for lists [like this one for example](https://www.nytimes.com/2018/06/18/watching/blaxpoitation-films-brown-sugar.html), use some simple scraping (like `[...document.querySelectorAll('h4[data-tag=subhead]')].map(n => n.innerHTML).join('\n')` to create a list of title year pairs, then run `traktarr newlist -f movies.txt --name "Classic Blaxploitation"`
This uses the the [tmdbsimple](https://pypi.org/project/tmdbsimple/) module to map names to tmdb ids and [trakt.py](https://github.com/fuzeman/trakt.py) to write to Trakt. I could drop the trakt.py dependency and implement it manually like you have in `media/trakt.py`

Would you accept a PR with these features?

**Comment by l3uddz** [comment]
Hey,

That sounds pretty useful, push it up to the develop branch and I will check it out, thanks.

I do like the sound of that first feature though.

**Comment by wishbones** [comment]
closing this as we're making progress in `feat/collections`
