### ISSUE TITLE
Couple Questions.

### ISSUE THREAD

**Issue by JourneyOver** [l3uddz/traktarr#44]
Ran across this when searching for a new trakt to sonarr option since flexget seems to have died on me for that purpose.. I haven't started using this yet as I have a few questions about a couple things..

1. Is there any way to disable the whole removal of shows/movies from trakt lists when adding them sonarr? I prefer to keep everything in my trakt lists well in my trakt lists as I usually go to said trakt list and sort by random when I am stuck on trying to figure out something to watch.

Or does this not remove them from the trakt lists but keeps a cache of shows/movies it's added and that's what I'm seeing from the demo thing when it says something like "removed existing radarr movies from trakt movies list"

2. Is there an option to set shows/movies to unmonitored (especially shows)? I sometimes prefer to have a show unmonitored until I at least see at least 1-2 episodes of a new show to determine if I'm going to watch it. 

3. Ontop of the unmonitored option thing, is there a way to set up multiple sonarr/radarr options for seperate trakt lists?

Example: 
```
"sonarr": {
    "api_key": "",
    "profile": "HD-1080p",
    "root_folder": "/tv/",
    "tags": {},
    "url": "http://localhost:8989/"
  },
"sonarr": {
    "api_key": "",
    "profile": "HD-1080p",
    "root_folder": "/anime/",
    "tags": {anime},
    "url": "http://localhost:8989/"
  }
```

as I have seperate trakt lists for shows and anime, and movies and anime movies, and I would want to set up the tagging for the anime lists while not having the tag set for normal shows.

3.5 Do tags have to have the whole "networks" thing with them, as like with 3 I'd like for it to just tag a whole list with that tag, and not just specific networks..

or would I have to go about setting up 4 seperate .config files for 3 and 3.5

4. Could this potentially work for windows? or is there specific things in the code that work only for Ubuntu/Debian

**Comment by 3daystoday** [comment]
Did you ever sort out 3 and 3.5? 

Kinda wondering the same,

**Comment by JourneyOver** [comment]
Nope, I ended up giving up on this since I never got an answer to anything, and i ended up getting flexgets plugin to work again, though all that seemed pointless now as well since I don't even have a computer now :s
