### ISSUE TITLE
Create a release?

### ISSUE THREAD

**Issue by fryfrog** [l3uddz/traktarr#45]
I'm exploring creating an AUR package for traktarr and it would be super keen if it could be based on an actual release. Is that something you'd consider? :)

**Comment by desimaniac** [comment]
Are you referring to creating Github Releases ?

**Comment by fryfrog** [comment]
Yup :)

**Comment by desimaniac** [comment]
Yeah we can do that.

**Comment by desimaniac** [comment]
Ok done. Earlier commit history got screwed up cause of a merge from someone who hadnt rebased properly. But later versions should be clean.
