### ISSUE TITLE
notifications to telegram?

### ISSUE THREAD

**Issue by RaymondSchnyder** [l3uddz/traktarr#64]
Hi,

I would like to ask if its possible to implement telegram notifications, as its a really good messenger with a public API.

Or maybe document how to write a custom notification plugin.

**Comment by desimaniac** [comment]
You can look at the notification examples. It's pretty modular, ie you can drop in another notification service without having to edit much else (other than init.py).

**Comment by desimaniac** [comment]
You can now use [Apprise](https://github.com/caronc/apprise) to add telegram notifications.
