### ISSUE TITLE
Only Sonarr and Shows

### ISSUE THREAD

**Issue by mouzzampk2014** [l3uddz/traktarr#66]
Hi, 
I just ran with docker compose and woke fine but I only want to keep shows and sonarr part from the conf file. Shall I delete the other lines? As Radarr already have Trakt list. And I also don't want the automatic list I only personal list? Thanks

**Comment by screwfaze** [comment]
I too would like to know the answer to this please. Only want private list.

Thanks

**Comment by desimaniac** [comment]
Set everything under automatic to 0.

**Comment by screwfaze** [comment]
Done that thanks. However nothing is being added to sonarr. My config is good I think task is running every hour but so far nothing has been added from trakkt

**Comment by desimaniac** [comment]
You need to authenticate yourself to use your private lists. Then add those lists to the config..

```
"automatic": {
  "movies": {
    "lists": {
```

**Comment by screwfaze** [comment]
Thanks for replying maybe I should open another issue because I have all the settings but nothing is adding to Sonarr. I have have the config below but nothing is happening and logs does not show any errors.

"automatic": {
    "movies": {
      "anticipated": 0,
      "boxoffice": 0,
      "interval": 0,
      "popular": 0,
      "trending": 0
    },
    "shows": {
      "anticipated": 0,
      "interval": 1,
      "popular": 0,
      "trending": 0,
      "lists": {
        "https://trakt.tv/users/********/watchlist": 10
     }

**Comment by mouzzampk2014** [comment]
> Thanks for replying maybe I should open another issue because I have all the settings but nothing is adding to Sonarr. I have have the config below but nothing is happening and logs does not show any errors. Only interested in TV shows from Trakt
> "automatic": {
> "movies": {
> "anticipated": 0,
> "boxoffice": 0,
> "interval": 0,
> "popular": 0,
> "trending": 0
> },
> "shows": {
> "anticipated": 0,
> "interval": 1,
> "popular": 0,
> "trending": 0,
> "lists": {
> "https://trakt.tv/users/********/watchlist": 10
> }

I am running on docker compose how you authenticate user? and could you please share your config as I am also looking for similar to your requirement :) Thank you

**Comment by screwfaze** [comment]
OK so I finally have an error message as you can see I have already done the authentication part. It must be the watchlist. Alsois 1 hour really the minimum you can do for schedule really hard to test with that.

2019-03-30 23:35:14,014 - ERROR      - helpers.trakt                       - extract_list_user_and_key_from_url  - The URL "https://trakt.tv/users/**********/watchlist" is not in the correct format

**Comment by screwfaze** [comment]
> > Thanks for replying maybe I should open another issue because I have all the settings but nothing is adding to Sonarr. I have have the config below but nothing is happening and logs does not show any errors. Only interested in TV shows from Trakt
> > "automatic": {
> > "movies": {
> > "anticipated": 0,
> > "boxoffice": 0,
> > "interval": 0,
> > "popular": 0,
> > "trending": 0
> > },
> > "shows": {
> > "anticipated": 0,
> > "interval": 1,
> > "popular": 0,
> > "trending": 0,
> > "lists": {
> > "https://trakt.tv/users/********/watchlist": 10
> > }
> 
> I am running on docker compose how you authenticate user? and could you please share your config as I am also looking for similar to your requirement :) Thank you

You have to follow the Guide from step 2 to step 3 on the readme. You will need terminal access to your docker so run  docker exec -it traktarr bash and you will be able to do the authentication part. When I get mine actually working I will give more information.

**Comment by mouzzampk2014** [comment]
> Thanks for replying maybe I should open another issue because I have all the settings but nothing is adding to Sonarr. I have have the config below but nothing is happening and logs does not show any errors. Only interested in TV shows from Trakt
> "automatic": {
> "movies": {
> "anticipated": 0,
> "boxoffice": 0,
> "interval": 0,
> "popular": 0,
> "trending": 0
> },
> "shows": {
> "anticipated": 0,
> "interval": 1,
> "popular": 0,
> "trending": 0,
> "lists": {
> "https://trakt.tv/users/********/watchlist": 10
> }
> 
> I am running on docker compose how you authenticate user? and could you please share your config as I am also looking for similar to your requirement :) Thank you
> 
> You have to follow the Guide from step 2 to step 3 on the readme. You will need terminal access to your docker so run  docker exec -it traktarr bash and you will be able to do the authentication part. When I get mine actually working I will give more information.

I am unable to access `docker exec -it traktarr bash`

**Comment by screwfaze** [comment]
> > Thanks for replying maybe I should open another issue because I have all the settings but nothing is adding to Sonarr. I have have the config below but nothing is happening and logs does not show any errors. Only interested in TV shows from Trakt
> > "automatic": {
> > "movies": {
> > "anticipated": 0,
> > "boxoffice": 0,
> > "interval": 0,
> > "popular": 0,
> > "trending": 0
> > },
> > "shows": {
> > "anticipated": 0,
> > "interval": 1,
> > "popular": 0,
> > "trending": 0,
> > "lists": {
> > "https://trakt.tv/users/********/watchlist": 10
> > }
> > I am running on docker compose how you authenticate user? and could you please share your config as I am also looking for similar to your requirement :) Thank you
> > You have to follow the Guide from step 2 to step 3 on the readme. You will need terminal access to your docker so run  docker exec -it traktarr bash and you will be able to do the authentication part. When I get mine actually working I will give more information.
> 
> I am unable to access `docker exec -it traktarr bash`

OK I am no expert  on docker so I would suggest using something like Portainer which gives you a console to your container and you can run commands from there. Maybe someone can give some better help here?

**Comment by mouzzampk2014** [comment]
> Thanks for replying maybe I should open another issue because I have all the settings but nothing is adding to Sonarr. I have have the config below but nothing is happening and logs does not show any errors. Only interested in TV shows from Trakt
> "automatic": {
> "movies": {
> "anticipated": 0,
> "boxoffice": 0,
> "interval": 0,
> "popular": 0,
> "trending": 0
> },
> "shows": {
> "anticipated": 0,
> "interval": 1,
> "popular": 0,
> "trending": 0,
> "lists": {
> "https://trakt.tv/users/********/watchlist": 10
> }
> I am running on docker compose how you authenticate user? and could you please share your config as I am also looking for similar to your requirement :) Thank you
> You have to follow the Guide from step 2 to step 3 on the readme. You will need terminal access to your docker so run  docker exec -it traktarr bash and you will be able to do the authentication part. When I get mine actually working I will give more information.
> 
> I am unable to access docker exec -it traktarr bash
> 
> OK I am no expert  on docker so I would suggest using something like Portainer which gives you a console to your container and you can run commands from there. Maybe someone can give some better help here?

Awe thank you. /bin/bash is missing :( that's why I cant access it

**Comment by mouzzampk2014** [comment]
If anyone need to authenticate using docker please use this `docker exec -it traktarr python traktarr.py trakt_authentication`. Thank you all sorted here

**Comment by desimaniac** [comment]
Reopened request.

**Comment by desimaniac** [comment]
Support for 0 interval has been added in.
