### ISSUE TITLE
seasons and episodes?

### ISSUE THREAD

**Issue by zw7u9tru** [l3uddz/traktarr#68]
Currently if you just add a season of a show via trakt, traktarr doesn't pick it up via the shows command.  

the api suggests:
```
Possible values: 

    movies , shows , seasons , episodes
```
as values for the call, but traktarr only uses shows for now.

is that something that would be easy to add?

**Comment by desimaniac** [comment]
You want to just add a show to Sonarr but monitor only a specific season ?

**Comment by pherralis** [comment]
Yes. For really long shows with 10 + seasons I don't want to track S1-9 when all I care about is 10.  I have metered downloading so I have to minimize the GB i dl/ul

**Comment by desimaniac** [comment]
There is already a request to just monitor the latest season (https://github.com/l3uddz/traktarr/issues/55). That’s some that could be looked into it. 

But don’t think we are going to do it on a per episode basis.
