### ISSUE TITLE
way to disable radarr but keep sonarr?

### ISSUE THREAD

**Issue by cppsse** [l3uddz/traktarr#71]
I've been running traktarr for about 24 hours now, really enjoying it.  I use sonarr but not radarr and I'd like to disable the radarr section so I can stop getting "connection refused" errors in my logs.  I've tried deleting the options in config.json but traktarr just adds them back in.  Any ideas?  Running traktarr, version 1.2.3

**Comment by desimaniac** [comment]
Set the movies list in the automatic section to 0 ...

```json
  "automatic": {
    "movies": {
      "anticipated": 0,
      "boxoffice": 0,
      "interval": 0,
      "popular": 0,
      "trending": 0
    },
```

**Comment by desimaniac** [comment]
`0` interval is now supported. 

Added in 86e33a8
