### ISSUE TITLE
Blacklist shows based on rating

### ISSUE THREAD

**Issue by tedrock** [l3uddz/traktarr#76]
Most categories are covered for blacklisting, but it’s surprising being able to blacklist based on rating isn’t an option.

**Comment by desimaniac** [comment]
You can set a minimum Rotten Tomatoes  score.

**Comment by tedrock** [comment]
From the documentation that appears to be for movies only.

**Comment by desimaniac** [comment]
Well now that you named your issue specifically, yes it is just for movies and that's because we use OMDD api to get the RT score. No RT scores available for TV Shows on Trakt or TVDB apis that we also use.

TVDB does have something called Site Rating for series, but not very useful.

**Comment by tedrock** [comment]
By trakt rating would be ideal. 

Also... "Well now that you renamed your issue specifically". Was that necessary? You are at fault here considering you replied 8 hours after I renamed it, it wasn't like I renamed it to make you wrong. I renamed the post 2 minutes after it was made to be more clear.

**Comment by desimaniac** [comment]
Perhaps I didn't read it properly the first time, so I guess I'm at "fault" here.
