### ISSUE TITLE
Addings shows without a country

### ISSUE THREAD

**Issue by Deviousretard** [l3uddz/traktarr#77]
Adding shows that do not have a country set in trakt results in an error and it ignores the show.

```
Traceback (most recent call last):
  File "/usr/local/bin/traktarr", line 306, in shows
    series['show']['country'].upper())
AttributeError: 'NoneType' object has no attribute 'upper'
```

This is while using the --ignore-blacklist command aswell.

**Comment by desimaniac** [comment]
Traktarr does not add TV shows or Movies that are missing a country. That is done to filter out incomplete entries. That error could be handled better, though.

**Comment by Deviousretard** [comment]
I managed to work around it myself by deleting some code from the traktarr.py

```
', '.join(series['show']['genres']), series['show']['network'],
series['show']['country'].upper
```
lines 305-306
Be sure to leave the ()) to close it up.

**Comment by desimaniac** [comment]
Should be fixed in develop branch.
