### ISSUE TITLE
Language support for sonarr v3

### ISSUE THREAD

**Issue by aconitumnapellus** [l3uddz/traktarr#80]
**Describe the problem**
Sonarr v3 took the languages out of the quality profile and put them into a seperate profile, this isnt supported by traktarr at the moment. When adding a series automated by traktarr, it is added as the default language, which is english and i dont want english, i want german.

**Describe any solutions you think might work**
Add an option to set the language profile

**Additional context**
Ombi has the same problem: https://github.com/tidusjar/Ombi/issues/2359
Currently, the v3 API is backwards compatible and takes the first language profile if none is specified.
As a workaround, i changed the language profiles so that german is the first

**Comment by desimaniac** [comment]
@aconitumnapellus Added that to f9c2449.

**Comment by desimaniac** [comment]
Added in https://github.com/l3uddz/traktarr/commit/44fb9a2fc74df90bb29d3346fec596f95a0d467f
