### ISSUE TITLE
Retrieve blacklist from radarr instead of adding manually in config (Blacklisted_tmdb_ids)

### ISSUE THREAD

**Issue by jobrien2001** [l3uddz/traktarr#84]
Hello,

Radarr has the ability to blacklist movies so they dont get added again.

Traktarr adds movies that have been blacklisted in radarr.  Traktarr should check if the movie has been blacklisted in radarr before adding.

Thanks

**Comment by jobrien2001** [comment]
Here is the api request and response from endpoint /api/exclusions
```
GET /api/exclusions HTTP/1.1
Host: 10.0.1.2:7878
Connection: keep-alive
Accept: application/json, text/javascript, */*; q=0.01
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
X-Api-Key: 7d42e88795be40bd8e342188dab4cb9d
Referer: http://10.0.1.2:7878/settings/netimport
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9,es;q=0.8
Cookie: _ncfaradarr=zS2N1OpZwdeIs0cEGS5EPE8c7vjVYg6HWbY8A2yV1Zw%3dVv65yj6wGdzaGa3c2FTofQl7vKrwNkknGGgnLEYFpCceVBv94Msj%2bwIqWM90RDrq; RadarrAuth=zS2N1OpZwdeIs0cEGS5EPE8c7vjVYg6HWbY8A2yV1Zw%3dVv65yj6wGdzaGa3c2FTofQl7vKrwNkknGGgnLEYFpCceVBv94Msj%2bwIqWM90RDrq
```

```
[
  {
    "tmdbId": 474976,
    "movieTitle": "With Love, Christmas",
    "movieYear": 2017,
    "id": 5
  },
  {
    "tmdbId": 474974,
    "movieTitle": "Miss Christmas",
    "movieYear": 2017,
    "id": 6
  },
  {
    "tmdbId": 474972,
    "movieTitle": "The Sweetest Christmas",
    "movieYear": 2017,
    "id": 7
  },
  {
    "tmdbId": 483554,
    "movieTitle": "Magical Christmas Ornaments",
    "movieYear": 2017,
    "id": 8
  },
  {
    "tmdbId": 474987,
    "movieTitle": "Marry Me at Christmas",
    "movieYear": 2017,
    "id": 9
  },
  {
    "tmdbId": 490147,
    "movieTitle": "Romance at Reindeer Lodge",
    "movieYear": 2017,
    "id": 10
  },
  {
    "tmdbId": 474983,
    "movieTitle": "Coming Home for Christmas",
    "movieYear": 2017,
    "id": 11
  },
  {
    "tmdbId": 475833,
    "movieTitle": "Christmas Encore",
    "movieYear": 2017,
    "id": 12
  },
  {
    "tmdbId": 481000,
    "movieTitle": "Good Witch: Spellbound",
    "movieYear": 2017,
    "id": 13
  },
  {
    "tmdbId": 507618,
    "movieTitle": "Feminists: What Were They Thinking?",
    "movieYear": 2018,
    "id": 14
  },
  {
    "tmdbId": 490818,
    "movieTitle": "Seeing Allred",
    "movieYear": 2018,
    "id": 15
  },
  {
    "tmdbId": 511791,
    "movieTitle": "Mercury 13",
    "movieYear": 2018,
    "id": 16
  }
]
```

**Comment by MollyBe** [comment]
Traktarr already filters movies that are in Radarr ([traktarr.py](https://github.com/l3uddz/traktarr/blob/25fc5548da8f9954e84fd120f20f0693c8175981/traktarr.py#L507)) 

`    # build filtered movie list without movies that exist in radarr
    processed_movies_list = radarr_helper.remove_existing_movies(pvr_objects_list, trakt_objects_list,
                                                                 callback_remove_recommended
                                                                 if remove_rejected_from_recommended else None)
    if processed_movies_list is None:
        log.error("Aborting due to failure to remove existing Radarr movies from retrieved Trakt movies list")
        if notifications:
            callback_notify({'event': 'abort', 'type': 'movies', 'list_type': list_type,
                             'reason': 'Failure to remove existing Radarr movies from retrieved '
                                       'Trakt %s movies list' % list_type})
        return None
    else:
        log.info("Removed existing Radarr movies from Trakt movies list, movies left to process: %d",
                 len(processed_movies_list))
`

This seems like the place to add it. 

I think it would be best to make it a variable, set to on by default. 

I've found another issue, which is related, and would most likely be addressed in the same filter above. 

Also when adding Trakt Lists to Radarr via Radarr, it will not add a movie if it doesn't match to TMDB. If you were to instead add the same list via Traktarr, it'll add the movie (unmatched to TMDB). I think it would be best to have the same behavior in Traktarr as seen in Radarr, it would be best as a variable, set to on by default.

**Comment by jobrien2001** [comment]
Also, some people might be using the "Blacklisted_tmdb_ids" in the config as it works right now so maybe good to keep that and concatenate that value with the radarr api value so manual input is still possible.

**Comment by desimaniac** [comment]
Added in f102452.

**Comment by desimaniac** [comment]
Added in  f102452.
