### ISSUE TITLE
Option to not import movies with broken TMDB URL. 

### ISSUE THREAD

**Issue by MollyBe** [l3uddz/traktarr#91]
**Describe the problem**

Often Trakt has entries with broken TMDB URLs. Radarr doesn't like having these imported.

**Describe any solutions you think might work**

Introduce an option to check if TMDB URL returns 404, if it does, don't import the movie.

**Additional context**

We can request these links are fixed on Trakt, but it takes a long time to have that happen. It would be best to not add them to Radarr. In the future Trakt may offer a better way to fix broken URLs but until then it would be easier to ignore all broken URLs.

**Comment by desimaniac** [comment]
https://twitter.com/themoviedb/status/1161718247097454592

**Comment by MollyBe** [comment]
Perhaps bad timing. 

Though this is unrelated. I am talking about trakt items pointing to incorrect TMBD URLs. Such as:
 
https://trakt.tv/movies/the-langoliers-1995
https://trakt.tv/movies/family-guy-presents-something-something-something-dark-side-2010
https://trakt.tv/movies/star-trek-renegades-2015

**Comment by desimaniac** [comment]
Yeah we can look into that...

**Comment by desimaniac** [comment]
Added in 8c33caed28df9b6af0e1edb6d660fb0e9d01a163
