### ISSUE TITLE
Automatic Traktlist breaking Traktarr

### ISSUE THREAD

**Issue by bluasoar** [l3uddz/traktarr#94]
So I installed the Traktarr Docker on my unRAID server Today and I got it working just using the CLI but wanted to try out the "Automatic" setting so I could just leave it and let it do it's thing. This is the config I am using when trying to use the Automatic mode https://pastebin.com/Es9Ut1ww and this is the error that that console gives me https://i.imgur.com/DJsap0z.png. I can use Traktarr fine when I don't input the "Lists" line but that seems to break it. Any ideas? Thanks guys

**Comment by desimaniac** [comment]
Line 12 in your config - Remove that comma. 

You can have your config checked at https://jsonformatter.curiousconcept.com/

**Comment by bluasoar** [comment]
> 
> 
> Line 12 in your config - Remove that comma.
> 
> You can have your config checked at https://jsonformatter.curiousconcept.com/

So I reinstalled Traktarr and I setup a new config here https://pastebin.com/Un31Pcf5 and I have absolutely no idea whats going on with it. I'm not at all familiar with the coding side of it. Thanks for the reply!

**Comment by desimaniac** [comment]
Add a comma after `"trending": 1`
