### ISSUE TITLE
Second Radarr instance

### ISSUE THREAD

**Issue by wellingssimon** [l3uddz/traktarr#97]
Hi
Recently setup traktarr. Working great adding to Radarr and Sonarr. Thanks very much!

My current setup currently involves a second instance of Radarr purely for 4K material. Is it possible to add this to traktarr also (separate radarr instance in the config json)? Or is a separate instance of traktarr required with a different config?

Appreciate your time.

**Comment by desimaniac** [comment]
You can run a separate instance by providing a different config file via --cachefile argument. See [here](https://github.com/l3uddz/traktarr#general-1).

**Comment by wellingssimon** [comment]
Thanks for the info and quick response, @desimaniac. I'll give that go. Other than that the program is working beautifully importing from Trakt. Great job!
